### PR TITLE
Queue url migration

### PR DESCRIPTION
**Pull request by ixtli**
As per discussion on #30 i've renamed all instances of `queue_name` to `queue_url` and changed the docs with a made up example url based on what the output of my `aws sqs list-queues` command kinda looks like. 

I ran `mix test` in both the top level dir and the examples dir. If there's any further testing I should do please let me know :)

### CODE REVIEW

**Comment by ixtli** [comment]
Also it occurs to me that it might be good to add a `with validation()` check to make a very explicit error message if someone upgrades and continues to use `queue_name`, however that'd probably be out of the scope of this pr.

**Comment by josevalim** [comment]
Maybe the best approach would be to keep it `queue_name` and then we see if it is a URL? If it is a URL, we pass it as is, otherwise we build it? This way we keep compatibility with previous API and documents. Thoughts?

**Comment by josevalim** [comment]
Please ignore me. @msaraiva has set me straight. :)

**Comment by msaraiva** [comment]
@ixtli thanks a lot for the PR ❤️

We'll push a new release today!

**Pull request merged**
